// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHpu3wQ48cnOs9elpl7YR3K1n6cnPPPaU',
    appId: '1:13643488551:web:53572d064d1ecc827bdd02',
    messagingSenderId: '13643488551',
    projectId: 'acitrack',
    authDomain: 'acitrack.firebaseapp.com',
    storageBucket: 'acitrack.firebasestorage.app',
    measurementId: 'G-EBENQYZDB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCNe7KkhYyP9YsBcUWLWH6ovxWjyJ1zR4',
    appId: '1:13643488551:android:0f5cb15a0b797c117bdd02',
    messagingSenderId: '13643488551',
    projectId: 'acitrack',
    storageBucket: 'acitrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkZLD8QjGrUMyU0Y4D6QDRSDGU60HXZ1I',
    appId: '1:13643488551:ios:355e885ecc680aa17bdd02',
    messagingSenderId: '13643488551',
    projectId: 'acitrack',
    storageBucket: 'acitrack.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkZLD8QjGrUMyU0Y4D6QDRSDGU60HXZ1I',
    appId: '1:13643488551:ios:355e885ecc680aa17bdd02',
    messagingSenderId: '13643488551',
    projectId: 'acitrack',
    storageBucket: 'acitrack.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHpu3wQ48cnOs9elpl7YR3K1n6cnPPPaU',
    appId: '1:13643488551:web:12ad595abe6285957bdd02',
    messagingSenderId: '13643488551',
    projectId: 'acitrack',
    authDomain: 'acitrack.firebaseapp.com',
    storageBucket: 'acitrack.firebasestorage.app',
    measurementId: 'G-0SB3YE620F',
  );
}
